config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'users/show'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all


  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :videos, only: [:show, :index] do
    resources :answer_users, only: [:create]
  end

  resources :users, only: [:show, :index]  do
    collection do
      get 'edit_profile'
      patch 'update_profile'
    end
    resources :bookmarks, only: [:index, :create]
  end

  resources :challenges, only: [:index, :show, :create]


  # resources :users, only: :show do

  # end

  resources :bookmarks, only: [:destroy, :update]
  get 'subscriptions/new', to: 'subscriptions#new'
  delete 'subscriptions/cancel' => 'subscriptions#cancel'
  post 'stripe_checkout' => 'subscriptions#stripe_checkout'
  post 'subscription_checkout' => 'subscriptions#subscription_checkout'
  post 'webhooks' => 'subscriptions#webhooks'
end

app/models/user.rb
class User < ApplicationRecord
  # include PgSearch
  # pg_search_scope :search_by_full_name, against: [:first_name, :last_name]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, presence: true
  has_many :bookmarks
  has_many :answer_users
  has_many :challenges
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  mount_uploader :photo, PhotoUploader

  after_create :send_welcome_email
  after_create :subscribe_to_newsletter

  def index
    @videos = Video.all
  end

  def show
  end

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_now
  end

  def subscribe_to_newsletter
    begin
      SubscribeToNewsletterService.new(self).call
    rescue Gibbon::MailChimpError => e
    end
  end

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20] # Fake password for validation
      user.save
    end

    return user
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_bookmarks, only: %I[show edit_profile]

  def show
    @user = current_user
    authorize @user
  end

  def index
    @users = policy_scope(User)
  end

  def edit_profile
    @user = current_user
    authorize @user
    render :show
  end

  def update_profile
    @user = User.find(current_user.id)

    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "users/edit_profile"
    end
    authorize @user
  end

  private
  
  def set_bookmarks
    @bookmarks = Bookmark.where(user_id: current_user.id, checked: true).all
  end
  
  def user_params
    params.required(:user).permit(:first_name, :last_name, :photo, :email)
  end
end

app/views/users/_edit_profile.html.erb
<div id="Profile-Edit" class="user-tabcontent-edit">
  <div class="user-edit-profile animated 1 zoomIn">
    <%= simple_form_for(@user, :url => '/users/update_profile') do |f| %>
      <% avatar_url =  current_user.photo.filename || current_user.facebook_picture_url || "https://www.w3schools.com/howto/img_avatar.png" %>
      <%= cl_image_tag avatar_url, height: 200, width: 200, crop: :fill, class: "user-avatar" %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <br/>
      <%= f.input :first_name, label: "First Name", value: @user.first_name %>
      <%= f.input :last_name, label: "Last Name", value: @user.last_name %>
      <%= f.input :email, label: "Email", value: @user.email %>
      <div class="secondary-button">
        <%= f.button :submit, "Submit Edits" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% title "Leaderboard" %>
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <table class="table table-hover" id="leaderboard">
        <thead>
          <tr>
            <th>Rank</th>
            <th colspan="1">User</th>
            <th>Score</th>
          </tr>
        </thead>
        <tbody>
          <% @users.order(score: :desc).each_with_index do |user, index| %>
          <% if current_user == user %>
            <tr id="current_user_leaderboard">
            <% else %>
            <tr>
          <% end %>
              <td><%= index + 1 %></td>
              <% if user.first_name == nil || user.last_name == nil %>
              <% username = user.email %>
              <% else %>
              <% username = "#{user.first_name} #{user.last_name}" %>
              <% end %>
              <% avatar_url = user.photo.filename || user.facebook_picture_url || "https://www.w3schools.com/howto/img_avatar.png" %>
              <td id="middle-column"><%= cl_image_tag avatar_url, height: 65, width: 65  %> <%= username %></td>
              <td><%= user.score %></td>
              <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% title "Your Account" %>
<div id="particles-js"></div>
<div class="user-container">
  <div class="user-wrapper">
    <h1>Your Account</h1>
    <div class="profile-tabs">
      <div class="user-tab">
        <button class="user-tablinks" onclick="openTab(event, 'Profile')" id="defaultOpen">Profile</button>
        <button class="user-tablinks" onclick="openTab(event, 'Progress')">Progress</button>
        <button class="user-tablinks" onclick="openTab(event, 'Bookmarks')">Bookmarks</button>
      </div>
    </div>
    <div id="Profile" class="user-tabcontent">
        <div class="user-profile animated 1 zoomIn">
          <% avatar_url = current_user.photo.filename || current_user.facebook_picture_url || "https://www.w3schools.com/howto/img_avatar.png" %>
          <%= cl_image_tag avatar_url, height: 200, width: 200, crop: :fill, class: "user-avatar" %>
          <br/>
          Name: <b><%= current_user.first_name || "(Not" %> <%= current_user.last_name || "supplied)" %></b>
          <br/>
          Email: <b><%= current_user.email %></b><br/>
          <%= link_to edit_profile_users_path, id: "profile-edit-btn" do %>
            <div class="secondary-button">
              Edit Profile
            </div>  
            <br/>
          <% end %>
          <% if !@user.plan_id.nil? %>
            <%= button_to "Cancel my Subscription", subscriptions_cancel_path, :data => { :confirm => "Are you sure?" }, :method => :delete, class: "btn btn-danger btn-xs" %>
          <% end %>
        </div>
    </div>
    <%=  render 'edit_profile' %> 
    <div id="Progress" class="user-tabcontent">
      <div class="user-progress">
        <div class="user-score">
          <%= current_user.score %>
        </div>
        Level: <b>
          <% if current_user.score < 200 %>
          <%= "Beginner" %>
          <% elsif current_user.score >= 200 && current_user.score < 400 %>
          <%= "Elementary" %>
          <% elsif current_user.score >= 400 && current_user.score < 600 %>
          <%= "Intermediate" %>
          <% elsif current_user.score >= 800 && current_user.score < 1000 %>
          <%= "Upper Intermediate" %>
          <% elsif current_user.score >= 1000 %>
          <%= "Advanced" %>
          <% end %>
        </b>
        <br/>
        <% sorted_by_score = User.order('users.score DESC').all %>
        <% rank = sorted_by_score.index(current_user) + 1 %>
        Rank: #
        <b>
          <%= rank %>
        </b>

        <%= link_to users_path do %>
          <div class="secondary-button">
            See Leaderboard
          </div>
        <% end %>
      </div>
    </div>
    <div id="Bookmarks" class="user-tabcontent">
      <div class="user-bookmarks">
        <% if @bookmarks.empty? %>
        <p>You have not bookmarked any videos yet.</p>
        <% end %>
        <% @bookmarks.each do |bookmark| %>
        <div data-bookmark-id="<%= bookmark.id %>" class="user-bookmark">
          <div class="bookmark-thumbnail">
            <%= link_to video_path(bookmark.video) do %>
            <img src="https://img.youtube.com/vi/<%= bookmark.video.url %>/hqdefault.jpg" width="100" height="60">
            <% end %>
          </div>
          <div class="bookmark-link">
            <%= link_to bookmark.video.title, video_path(bookmark.video) %>
            <div class="bookmark-difficulty">
              <%= "Beginner" if bookmark.video.difficulty > -1 && bookmark.video.difficulty < 200 %>
              <%= "Elementary" if bookmark.video.difficulty > 199 && bookmark.video.difficulty < 400 %>
              <%= "Intermediate" if bookmark.video.difficulty > 399 && bookmark.video.difficulty < 600 %>
              <%= "Advanced" if bookmark.video.difficulty > 599 && bookmark.video.difficulty < 800 %>
              <%= "Expert" if bookmark.video.difficulty > 799 && bookmark.video.difficulty < 1000 %>
            </div>
          </div>
          <div class="delete-bookmark-button">
            <%= link_to bookmark_path(bookmark), remote: true, class: "delete-bookmark-button", method: :delete do %>
            <i class="fas fa-times-circle fa-2x"></i>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  function openTab(evt, tabName) {
    var i, tabcontent, tablinks;

    profileEdit = document.getElementById("Profile-Edit")

    tabcontent = document.getElementsByClassName("user-tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
      tabcontent[i].style.display = "none";
      profileEdit.style.display = "none";
    }

    tablinks = document.getElementsByClassName("user-tablinks");
    for (i = 0; i < tablinks.length; i++) {
      tablinks[i].className = tablinks[i].className.replace(" active", "");
    }

    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
  }
  document.getElementById("defaultOpen").click();
</script>