config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'users/show'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all


  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :videos, only: [:show, :index] do
    resources :answer_users, only: [:create]
  end

  resources :users, only: [:show, :index]  do
    collection do
      get 'edit_profile'
      patch 'update_profile'
    end
    resources :bookmarks, only: [:index, :create]
  end

  resources :challenges, only: [:index, :show, :create]


  # resources :users, only: :show do

  # end

  resources :bookmarks, only: [:destroy, :update]
  get 'subscriptions/new', to: 'subscriptions#new'
  delete 'subscriptions/cancel' => 'subscriptions#cancel'
  post 'stripe_checkout' => 'subscriptions#stripe_checkout'
  post 'subscription_checkout' => 'subscriptions#subscription_checkout'
  post 'webhooks' => 'subscriptions#webhooks'
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :questions
  has_many :bookmarks
  has_many :challenges
  validates :title, presence: true
  validates :url, uniqueness: true, presence: true
  validates :difficulty, presence: true
  validates :category, presence: true
  validates :region, presence: true
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_videos, only: [:show]

  def index
    @videos = policy_scope(Video)
    if @videos
      if params["min_difficulty"]
        @videos = policy_scope(Video.where("difficulty BETWEEN ? AND ?", params["min_difficulty"], params["max_difficulty"]))
      elsif params["score"]
        vids = Video.find_by_sql("SELECT * FROM videos ORDER BY (difficulty - #{params["score"]}) ASC LIMIT 5")
        @videos = policy_scope(Video.where(id: vids.map(&:id)))
      elsif params["category"]
        @videos = policy_scope(Video.where(category: params["category"]))
      elsif params["region"]
        @videos = policy_scope(Video.where(region: params["region"]))
      else
        @videos
      end
    else
      redirect_to subscriptions_new_path
    end
  end

  def show
    @bookmark = Bookmark.find_by(video_id: @video.id, user_id: current_user.id) || Bookmark.new(video_id: @video.id, user_id: current_user.id, checked: false)
    @bookmark.save
    @bookmarks = Bookmark.where(user_id: current_user.id).all
    @questions = @video.questions
    @challenge = Challenge.new
    @answer = Answer.new
    @users = User.all
    @points
  end

  def set_videos
    @video = Video.find(params[:id])
    authorize @video
  end
end

app/views/videos/_done_quiz.html.erb
<div class="done-quiz">
  <% @points = 0 %>
  <% @questions.each do |question| %>
    <div class="quiz-form">
      <h3><%= question.question %></h3>
      <% question.answers.each_with_index do |statement, index| %>
        <% if AnswerUser.find_by(answer: statement, user: current_user) && statement.correct %>
          <p class="quiz-correct-chosen"><%= statement.answer %></p>
          <% @points += 1 %>
        <% elsif AnswerUser.find_by(answer: statement, user: current_user) && !statement.correct %>
          <p class="quiz-incorrect-chosen"><%= statement.answer %></p>
        <% elsif !AnswerUser.find_by(answer: statement, user: current_user) && statement.correct %>
          <p class="quiz-correct-not-chosen"><%= statement.answer %></p>
        <% else %>
          <p><%= statement.answer %></p>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <div class="quiz-score-stuff">
    <div class="quiz-score">
      <div class="quiz-score-content">
        <%= image_tag "#{@points.to_s}-points.png", width: "80", height: "80" %>
        <br/>You scored <b><%= @points %></b> point(s).<br/>
        Your overall score is now <b><%= current_user.score %></b>.
        <% if @points < 2 %>
          <% new_score = @video.difficulty += 1 %>
          <% @video.update(difficulty: new_score) %>
        <% elsif @points > 2 %>
          <% new_score = @video.difficulty -= 1 %>
          <% @video.update(difficulty: new_score) %>
        <% else %>
        <% end %>
      </div>
      <br/>
      <div class="done-quiz-back-button">
        <%= link_to "Back to videos", videos_path, class: "btn btn-primary gray" %>
      </div>
    </div>
    <div class="quiz-next-video">
      <div class="next-video-container">
        <div class="next-video-info">
          <b>NEXT RECOMMENDED ></b>
        </div>
        <div class="next-video-thumbnail">
          <% recommended_array = Video.find_by_sql("SELECT * FROM videos ORDER BY (difficulty - #{current_user.score})") %>
          <% current_index = recommended_array.find_index(@video) %>
          <% next_video = recommended_array[current_index + 1] %>
          <%= link_to video_path(next_video) do %>
            <img src="https://img.youtube.com/vi/<%= next_video.url %>/hqdefault.jpg" width="180" height="120">
          <% end %>
        </div>
        <div class="done-quiz-right-button">
          <%= link_to "Let's go!", video_path(next_video), class: "btn btn-primary lets-go" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/videos/_done_quiz___sebas.html.erb
<div class="done-quiz">
  <% @points = 0 %>
  <% @questions.each do |question| %>
    <div class="quiz-form">
      <h3><%= question.question %></h3>
      <% question.answers.each_with_index do |statement, index| %>
        <% if AnswerUser.find_by(answer: statement, user: current_user) && statement.correct %>
          <p class="quiz-correct-chosen"><%= statement.answer %></p>
          <% @points += 1 %>
        <% elsif AnswerUser.find_by(answer: statement, user: current_user) && !statement.correct %>
          <p class="quiz-incorrect-chosen"><%= statement.answer %></p>
        <% elsif !AnswerUser.find_by(answer: statement, user: current_user) && statement.correct %>
          <p class="quiz-correct-not-chosen"><%= statement.answer %></p>
        <% else %>
          <p><%= statement.answer %></p>
        <% end %>
      <% end %>
    </div>
  <% end %>
  <div class="quiz-score-stuff">
    <div class="quiz-score">
      <div class="quiz-score-content">
        <%= image_tag "#{@points.to_s}-points.png", width: "80", height: "80" %>
        <br/>You scored <b><%= @points %></b> point(s).<br/>
        Your overall score is now <b><%= current_user.score %></b>.
        <% if @points < 2 %>
          <% new_score = @video.difficulty += 1 %>
          <% @video.update(difficulty: new_score) %>
        <% elsif @points > 2 %>
          <% new_score = @video.difficulty -= 1 %>
          <% @video.update(difficulty: new_score) %>
        <% else %>
        <% end %>
      </div>
      <br/>
      <div class="done-quiz-back-button">
        <%= link_to "Back to videos", videos_path, class: "btn btn-primary gray" %>
      </div>
    </div>
    <div class="quiz-next-video">
      <div class="next-video-container">
        <div class="next-video-info">
          <b>NEXT RECOMMENDED ></b>
        </div>
        <div class="next-video-thumbnail">
          <% recommended_array = Video.find_by_sql("SELECT * FROM videos ORDER BY (difficulty - #{current_user.score})") %>
          <% current_index = recommended_array.find_index(@video) %>
          <% next_video = recommended_array[current_index + 1] %>
          <%= link_to video_path(next_video) do %>
            <img src="https://img.youtube.com/vi/<%= next_video.url %>/hqdefault.jpg" width="180" height="120">
          <% end %>
        </div>
        <div class="done-quiz-right-button">
          <%= link_to "Let's go!", video_path(next_video), class: "btn btn-primary lets-go" %>
        </div>
      </div>
    </div>
  </div>
  <div class="challenge-stuff">
    <div class="done-quiz-challenge">
      <h3>Share this video with a friend and see if they can beat your score!</h3>
      <div id="challenge-button" class="btn btn-primary" onclick="showChalForm()">
        Challenge a friend
      </div>
      <div id="challenge-form" class="done-quiz-challenge-form">
        <%= simple_form_for(@challenge, remote: true) do |f| %>
        <%= f.hidden_field :video_id, value: @video.id %>
        <!-- <%= f.input :opponent_id, label: "Opponent ID", required: true %> -->
        <%= f.input :opponent_id, collection: User.all, :required => true, label_method: :email, value_method: :id, input_html: { id: 'challenge-select' } %>
        <%= f.button :submit, "Challenge this user", class: 'search-button' %>
        <% end %>
        <div id="challenge-response" class="done-quiz-challenge-form-2">
        </div>
      </div>
    </div>
  </div>
</div>
<script>
function showChalForm() {
  document.getElementById("challenge-form").style.display = 'block';
  document.getElementById("challenge-button").style.display = 'none';
}
</script>
<script>
  challengeSelect = document.getElementById("challenge-select")
  challengeSelect.select2();
</script>
<script>
  $(document).ready(function() {
    $('.opponent-dropdown').select2();
});
</script>

app/views/videos/_todo_quiz.html.erb
<%= simple_form_for :answer, url: video_answer_users_path(@video), remote: true do |f| %>
  <% @questions.each_with_index do |question, index| %>
  <% qindex = index %>
    <div class="quiz-form">
      <h3><%= question.question %></h3>
      <input type="hidden" name="question-<%= qindex %>[answer]" value="" />
      <% question.answers.each_with_index do |statement, index| %>
        <span>
          <input type="radio" value="<%= index %>" name="question-<%= qindex %>[answer]" id="question-<%= qindex %>-<%= statement.id %>" />
          <label class="collection_radio_buttons" for="question-<%= qindex %>-<%= statement.id %>"><%= statement.answer %></label><br/>
        </span>
      <% end %>
    </div>
  <% end %>
  <br/>
  <%= f.submit "Submit Answers", class:"quiz-submit" %>
<% end %>

app/views/videos/_todo_quiz__old.html.erb
<%= simple_form_for :answer, url: video_answer_users_path(@video) do |f| %>
  <% @questions.each do |question| %>
    <div class="quiz-form">
      <h3><%= question.question %></h3>
      <input type="hidden" name="question-<%= question.id %>[answer]" value="" />
      <% question.answers.each_with_index do |statement, index| %>
        <span>
          <input type="radio" value="<%= index %>" name="question-<%= question.id %>[answer]" id="question-<%= question.id %>-<%= statement.id %>" />
          <label class="collection_radio_buttons" for="question-<%= question.id %>-<%= statement.id %>"><%= statement.answer %></label><br/>
        </span>
      <% end %>
    </div>
  <% end %>
<br/>
<%= f.submit "Submit Answers", class:"quiz-submit" %>
<% end %>

app/views/videos/index.html.erb
<div class="main-container">
  <div id="list">
    <% title "Videos" %>
    <h5><%= link_to videos_path do %>
     <i class="fas fa-home"></i> Home
     <%end %></h5>
    <h5><%= link_to videos_path(score: current_user.score) do %> <i class="fas fa-thumbs-up"></i> Recommended<% end %></h5>
    <h5> <%= link_to videos_path(category:[ "Sport","Movies"]) do %><i class="fas fa-chart-line"></i> Trend <%end %></h5>

      <h3>Difficulty</h3>
    <ul>
      <li><%= link_to "Beginner", videos_path(min_difficulty: 1, max_difficulty: 199) %> </li>
      <li><%= link_to "Elementary", videos_path(min_difficulty: 200, max_difficulty: 399) %></li>
      <li><%= link_to "Intermediate", videos_path(min_difficulty: 400, max_difficulty: 599) %></li>
      <li><%= link_to "Advanced", videos_path(min_difficulty: 600,max_difficulty: 799) %></li>
      <li><%= link_to "Expert", videos_path(min_difficulty: 800, max_difficulty: 999) %></li>
    </ul>
      <h3>Category</h3>

      <h5> <%= link_to videos_path(category: "Animation") do %>
      <i class="fab fa-napster"></i> Animation <% end %> </li>
      <h5> <%= link_to videos_path(category: "Comedy") do %>
      <i class="far fa-smile"></i> Comedy <% end %></h5>
      <h5> <%= link_to videos_path(category: "Song") do %>
        <i class="fas fa-music"></i> Songs <% end %></h5>
      <h5> <%= link_to  videos_path(category: "Sports") do  %>
        <i class="fas fa-football-ball"></i> Sports <% end %></h5>
      <h5> <%= link_to videos_path(category: "Movies") do %>
      <i class="fas fa-film"></i> Movies <% end %></h5>
      <h5> <%= link_to videos_path(category: "News") do %>
      <i class="far fa-newspaper"></i> News<% end %> </h5>
      <h5> <%= link_to videos_path(category: "Tech") do %>
        <i class="fas fa-laptop"></i> Tech <% end %></h5>
      <h5> <%= link_to videos_path(category: "Poetry") do%>
      <i class="fas fa-book-open"></i> Poetry <% end %> </h5>

      <h3>Region </h3>
    <ul>
      <li> <%= link_to "Argentina", videos_path(region: "Argentina") %> </li>
      <li> <%= link_to "Colombia", videos_path(region: "Colombia") %> </li>
      <li> <%= link_to "Mexico", videos_path(region: "Mexico") %> </li>
      <li> <%= link_to "Puerto Rico", videos_path(region: "Puerto Rico") %> </li>
      <li> <%= link_to "Spain", videos_path(region: "Spain") %> </li>
    </ul>
  </div>

    <div class="card-container">
      <div class="row" id="video-index">
        <h2>Videos</h2>
        <% @videos.each do |video| %>
        <div class="col-xs-12 col-sm-4 card-outline">
          <div class="videos-title">
                  <%= video.title %>
          </div>
          <% if video.difficulty < (current_user.score + 700) %>
            <%= link_to video_path(video) do %>
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url( 'https://img.youtube.com/vi/<%= video.url %>/hqdefault.jpg')">
                <div class="card-category">
                  <%= video.category %>
                </div>
                <div class="card-description">
                  <div class= "far fa-play-circle"> </div>
                  </div>
              </div>
            <% end %>
          <% else %>
            <div class="card locked-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url( 'https://img.youtube.com/vi/<%= video.url %>/hqdefault.jpg')">
              <div class="card-category">
                <%= video.category %>
              </div>
              <div class="card-description">
              </div>
              <div class="videos-title">
              </div>
            </div>
            <div id="lock" class="lock">
                  <div class="popup" onclick="clickLock()">
                    <%= image_tag "lock.png", height: '50', width: '50', class: "lock" %>
                    <span class="popuptext" id="myPopup">
                      <% pointsneeded = video.difficulty - (current_user.score + 700) %>
                <b>This video is locked!</b><br/><br/><%= image_tag "lock.png", height: '120', width: '120', class: "gold" %><br/><br/>You need another <%= pointsneeded %> points to unlock it.  Keep working!
                    </span>
                  </div>
                </div>
            <% end %>
          </div>
          <% end %>
      </div>
   </div>
</div>
<script>
function clickLock() {
    var popup = document.getElementById("myPopup");
    popup.classList.toggle("show");
}
</script>

app/views/videos/show.html.erb
<div class="video-container">
  <div class="video-wrapper">
    <% title @video.title %>
    <h1><%= @video.title %></h1>
    <div class="video-details">
      <div class="video-category">
        <%= @video.category %>
      </div>
      <div class="video-difficulty">
        <%= "Beginner" if @video.difficulty > -1 && @video.difficulty < 200 %>
        <%= "Elementary" if @video.difficulty > 199 && @video.difficulty < 400 %>
        <%= "Intermediate" if @video.difficulty > 399 && @video.difficulty < 600 %>
        <%= "Advanced" if @video.difficulty > 599 && @video.difficulty < 800 %>
        <%= "Expert" if @video.difficulty > 799 && @video.difficulty < 1000 %>
      </div>
      <div class="video-bookmark">
        <%= link_to bookmark_path(@bookmark), remote: true, method: :put do %>
          <div id="bookmark-cont" class="<%= @bookmark.checked? ? 'bookmark-inactive' : 'bookmark-active' %>">
            <i id="bookmark" class="<%= @bookmark.checked? ? 'fas' : 'far' %> fa-star fa-1x"></i>
          </div>
        <% end %>
      </div>
    </div>
    <div class="video-player">

      <iframe width="640" height="340" src="https://www.youtube.com/embed/<%= @video.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


    </div>
    <div class="learning-section">
      <div class="tab">
        <button class="tablinks" onclick="openTab(event, 'Quiz')" id="defaultOpen">Quiz</button>
        <button class="tablinks" onclick="openTab(event, 'Transcript')">Transcript</button>
      </div>
      <div id="Quiz" class="tabcontent">
        <div id="Quiz-top">
          <% quiz_done = false %>
          <% @video.questions.each do |question| %>
            <% question.answers.each do |answer| %>
              <% if AnswerUser.find_by(answer: answer, user: current_user) %>
                <% quiz_done = true %>
              <% end %>
            <% end %>
          <% end %>
          <% if quiz_done == false %>
            <%= render 'todo_quiz' %>
          <% else %>
            <div class="done-banner">
              You have already completed this quiz.  Your scores are below.
            </div>
            <%= render 'done_quiz' %>
          <%end%>
        </div>
          <div id="challenge-stuff" class="challenge-stuff">
            <div class="done-quiz-challenge">
              <h3>Share this video with a friend and see if they can beat your score!</h3>
              <div id="challenge-button" class="btn btn-primary">
                Challenge a friend
              </div>
              <div id="challenge-form" class="done-quiz-challenge-form">
                <%= simple_form_for(@challenge, remote: true) do |f| %>
                <%= f.hidden_field :video_id, value: @video.id %>
                <select class='select2' name="challenge[opponent_id]">
                  <% @users.each do |u| %>
                    <option value="<%= u.id %>"><%= u.first_name %> <%= u.last_name || u.email %></option>
                  <% end %>

                </select>
                <%= f.button :submit, "Challenge this user", class: 'search-button' %>
                <% end %>
                <div id="challenge-response" class="done-quiz-challenge-form-2">
                </div>
              </div>
            </div>
          </div>
      </div>
      <div id="Transcript" class="tabcontent">
        <h5 class="text-center" style="color: black">Click on a word to translate!</h5>
        <!-- <%= simple_format(@video.transcript) %> -->
        <% @video.transcript.split.each do |word| %>
          <span class='word' data-toggle='popover' data-content='test'><%= word %></span>
        <% end %>

      </div>
    </div>
  </div>
</div>
<script>
  function openTab(evt, tabName) {
      var i, tabcontent, tablinks;

      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
          tabcontent[i].style.display = "none";
      }

      tablinks = document.getElementsByClassName("tablinks");
      for (i = 0; i < tablinks.length; i++) {
          tablinks[i].className = tablinks[i].className.replace(" active", "");
      }

      document.getElementById(tabName).style.display = "block";
      evt.currentTarget.className += " active";
  }
  document.getElementById("defaultOpen").click();
</script>