config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'users/show'
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all


  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :videos, only: [:show, :index] do
    resources :answer_users, only: [:create]
  end

  resources :users, only: [:show, :index]  do
    collection do
      get 'edit_profile'
      patch 'update_profile'
    end
    resources :bookmarks, only: [:index, :create]
  end

  resources :challenges, only: [:index, :show, :create]


  # resources :users, only: :show do

  # end

  resources :bookmarks, only: [:destroy, :update]
  get 'subscriptions/new', to: 'subscriptions#new'
  delete 'subscriptions/cancel' => 'subscriptions#cancel'
  post 'stripe_checkout' => 'subscriptions#stripe_checkout'
  post 'subscription_checkout' => 'subscriptions#subscription_checkout'
  post 'webhooks' => 'subscriptions#webhooks'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">

    <a href="https://www.instagram.com" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com" target="_blank"><i class="fab fa-facebook"></i></a>
    <a href="https://www.twitter.com" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.youtube.com" target="_blank"><i class="fab fa-youtube"></i></a>
  </div>
  <div class="footer-powered">
    <ol class="hidden-xs">Sponsored by Le Wagon <%= image_tag "logo-wagon.png", height: 25 %> </ol>
  </div>
  <div class="footer-copyright">
    <ul>
    <ol>Miranda <i class="fas fa-registered"></i></ol>
  </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to videos_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="miranda-text animated infinite pulse">
    Miranda
  </div>

  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="navbar-points">
          <i class="fas fa-trophy gold-trophy"></i>
          <%= current_user.score %>
        </div>
        <div class="challenges">
            <%= link_to challenges_path do %>
                <i class="fas fa-chalkboard-teacher" style="color: blue; padding-right: 4px" ></i>
                <%= Challenge.get_pending(current_user).first.count %>
              <% end %>
        </div>
        <div class="dropdown">
         <% avatar_url = current_user.photo.filename || current_user.facebook_picture_url || "https://www.w3schools.com/howto/img_avatar.png" %>
          <%= cl_image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to users_show_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>

             <li> <%= link_to challenges_path do %>
                <i class="fas fa-chalkboard-teacher"></i> Challenges <%end  %>
             </li>

            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "login_navbar", id: "login_navbar_md"%>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg" style="padding-left: 8em">
    <% if user_signed_in? %>
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

          <li><%= link_to users_show_path do %>
                  <i class="fa fa-user"></i><%= t(".profile", default: "Profile") %>
                <% end %>
          </li>

          <li><%= link_to  edit_profile_users_path do %>
                <i class="fa fa-cog"></i><%= t(".settings", default: "Settings") %>
              <% end %>
          </li>

          <li><%= link_to challenges_path do %>
                <i class="fas fa-chalkboard-teacher"></i> Challenge
              <%end %>
          </li>


          <li><%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i></i><%= t(".sign_out", default: "Log out") %>
                <% end %>
          </li>
        </ul>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "login_navbar" %>
    <% end %>
  </div>
</div>